### ISSUE TITLE
Customize Tailwind theme

### ISSUE THREAD

**Issue by MuhannedNoman** [Iraq-RBC-Capstones-2021/capstone-react-libvery#1]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe how the solution should behave**
Add the color palette of the project from the Figma design to tailwind allowing us to use primary, secondary...etc. Also, if there is a custom font implement it.

**Screenshots of the design/if any**
N/A

**Additional context**
[This link might be helpful](https://tailwindcss.com/docs/theme)

**Comment by RawandDev** [comment]
bug: can't use other tailwind colors. We can only use 4 colors.
