### ISSUE TITLE
Create the Navbar component.

### ISSUE THREAD

**Issue by MuhannedNoman** [Iraq-RBC-Capstones-2021/capstone-react-libvery#4]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe how the solution should behave**
The navbar should be responsive on desktop, tablet, and phone. Also, make sure the navbar is reacting to when the user login, so that the login button change. Let's set up the main routes of this in the `pages` folder as well. So create a folder for each page and have an index file inside with the name of the page as an `h1` for now.

**Screenshots of the design/if any**
![image](https://user-images.githubusercontent.com/40465727/136108272-995d81fe-2e88-4cb5-a49b-7c4e5c53d2ce.png)

**Additional context**
[This link might help](https://tailwindui.com/components/application-ui/navigation/navbars)

**Comment by RawandDev** [comment]
Closing this issue according to [this](https://github.com/Iraq-RBC-Capstones-2021/capstone-react-libvery/pull/38) PR
