### ISSUE TITLE
Connect the user profile.

### ISSUE THREAD

**Issue by MuhannedNoman** [Iraq-RBC-Capstones-2021/capstone-react-libvery#49]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe how the solution should behave**
The user should be able to update their data, user email, and phone number. Once the update is live in firestore, the redux should be updated as well.

**Screenshots of the design/if any**
![image](https://user-images.githubusercontent.com/40465727/137628449-77fc82d2-0668-456a-a5a0-f6bd51ef85a5.png)

**Additional context**
The user info should be in the User slice once the user is authenticated.

**Comment by RawandDev** [comment]
closing according to [#61](https://github.com/Iraq-RBC-Capstones-2021/capstone-react-libvery/pull/61)
